services:
#    oi_platform.example:
#        class: OI\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  oi_platform.antispam:
    class: OI\PlatformBundle\Service\Antispam
    arguments: [20] # tableau d'arguments alimentant le constructeur de la classe
